export const NAVIGATION_SUMMARY_SCREEN = 'NAVIGATION_SUMMARY_SCREEN'
export const NAVIGATION_HISTORY = 'NAVIGATION_HISTORY'
export const NAVIGATION_SETTING_CHAT = 'NAVIGATION_SETTING_CHAT'
export const NAVIGATION_LOGIN_SCREEN = 'NAVIGATION_LOGIN_SCREEN'
export const NAVIGATION_CHOOSE_COUNTRY_SCREEM = 'NAVIGATION_CHOOSE_COUNTRY_SCREEM'
export const NAVIGATION_HISTORY_SCREEN = 'NAVIGATION_HISTORY_SCREEN'
export const NAVIGATION_ECOSYSTEM = 'NAVIGATION_ECOSYSTEM'
export const NAVIGATION_EDIT_PROFILE = 'NAVIGATION_EDIT_PROFILE'
export const NAVIGATION_SETTING_FONT_SIZE = 'NAVIGATION_SETTING_FONT_SIZE'
export const NAVIGATION_SETTING_FONT = 'NAVIGATION_SETTING_FONT'
export const NAVIGATION_SETTING_SPEED = 'NAVIGATION_SETTING_SPEED'
export const NAVIGATION_EDIT_TEXT_SCREEN = 'NAVIGATION_EDIT_TEXT_SCREEN'
export const NAVIGATION_DELETE_ACCOUNT = 'NAVIGATION_DELETE_ACCOUNT'
export const NAVIGATION_SETTINGS_SCREEN = 'NAVIGATION_SETTINGS_SCREEN'
export const NAVIGATION_SETTINGS_THEME = 'NAVIGATION_SETTINGS_THEME'
export const NAVIGATION_SETTINGS_SYSTEM = 'NAVIGATION_SETTINGS_SYSTEM'
export const NAVIGATION_UPDATE_VOICE = 'NAVIGATION_UPDATE_VOICE'
export const NAVIGATION_PREMIUM_SERVICE_SCREEN = 'NAVIGATION_PREMIUM_SERVICE_SCREEN'
export const NAVIGATION_PREMIUM_SUCCESS_SCREEN = 'NAVIGATION_PREMIUM_SUCCESS_SCREEN'
export const NAVIGATION_LOADING = 'NAVIGATION_LOADING'
export const NAVIGATION_BLANK = 'NAVIGATION_BLANK'
export const NAVIGATION_WELCOME = 'NAVIGATION_WELCOME'

export const NumOfRoute= {
    [NAVIGATION_WELCOME]: '_WEL',
    [NAVIGATION_CHOOSE_COUNTRY_SCREEM]: '_COUTR',
    [NAVIGATION_HISTORY_SCREEN]: '_HIS',
    [NAVIGATION_EDIT_PROFILE]: '_EDIT',
    [NAVIGATION_EDIT_TEXT_SCREEN]: '_EDTEX',
    [NAVIGATION_SETTINGS_SCREEN]: '_SETT',
    [NAVIGATION_SETTINGS_SYSTEM]: '_SETSY',
    [NAVIGATION_PREMIUM_SERVICE_SCREEN]: '_PRE',
    [NAVIGATION_LOADING]: '_LOAD',
    [NAVIGATION_PREMIUM_SUCCESS_SCREEN]: '_SUCC',
    [NAVIGATION_SUMMARY_SCREEN]: '_SUM',
    [NAVIGATION_HISTORY]: '_HIS',
    [NAVIGATION_SETTING_CHAT]: '_SETC',
    [NAVIGATION_SETTING_FONT_SIZE]: '_SETFS',
    [NAVIGATION_SETTING_FONT]: '_SETF',
    [NAVIGATION_SETTING_SPEED]: '_SETSP',
    [NAVIGATION_SETTINGS_THEME]: '_SETTH',
    [NAVIGATION_UPDATE_VOICE]: '_VOI',
    [NAVIGATION_BLANK]: '_BLAN',
}
